### ISSUE TITLE
`cta` block type html and metadata correspondance

### ISSUE THREAD

**Issue by forresto** [the-grid/html-flatten#72]
We need to define how cta blocks are saved, and make sure html-flatten works as expected.

```
type: 'cta'
html: '<a href="url" data-role="cta" data-cta-modal="true">take an action!</a>'
metadata:
  openAsModal: true
  url: 'url'
  label: 'take an action!'
```

I like the link way, since the raw html from API will work.
